---
hero_image: images/fortune-teller.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Fortune Teller
description: Use your micro:bit to read the future!
original_url: https://codeclubprojects.org/en-GB/microbit/fortune-teller
interests: ''
technologies: ''
site_areas: codeclub, microbit
steps:
- title: Introduction
- title: Scrolling text
- title: Making a decision
- title: 'Challenge: Multiple answers'
- title: 'Challenge: Shake your micro:bit'
