---
hero_image: images/fortune-teller.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Wahrsager
description: Benutze deinen micro:bit, um die Zukunft vorherzusagen!
original_url: https://codeclubprojects.org/en-GB/microbit/fortune-teller
interests: ''
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-02-28
steps:
- title: Einleitung
- title: Lauftext
- title: Eine Entscheidung treffen
  completion:
  - engaged
  - internal
- title: 'Herausforderung: Mehrere Antworten'
- title: 'Herausforderung: Schüttele deinen micro:bit'
