---
hero_image: images / fortune-teller.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, disseny-0, programació-1, phys-comp-0, fabricació-0, comunitat-0
title: Fortune Teller
description: Use your micro:bit to read the future!
original_url: https://codeclubprojects.org/en-GB/microbit/fortune-teller
interests: ''
technologies: microbit
site_areas: projectes
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-02-28
steps:
  - 
    title: Introducció
  - 
    title: Scrolling text
  - 
    title: Making a decision
  - 
    title: 'Challenge: Multiple answers'
  - 
    title: 'Challenge: Shake your micro:bit'
